// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-teams.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Liga a tua conta TacticaFlow via OAuth." }
    ],
    isError: true
  };
}
function dbError(message) {
  return { content: [{ type: "text", text: `Erro: ${message}` }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-teams.ts
var list_teams_default = defineTool({
  name: "list_teams",
  title: "Listar equipas",
  description: "Lista as equipas acess\xEDveis ao utilizador autenticado (nome, escal\xE3o, modalidade, \xE9poca).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("N\xFAmero m\xE1ximo de equipas a devolver (por omiss\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("teams").select("id, name, category, gender, sport_type, season, formation").order("name").limit(limit ?? 50);
    if (error) return dbError(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-players.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var list_players_default = defineTool2({
  name: "list_players",
  title: "Listar jogadores",
  description: "Lista jogadores acess\xEDveis ao utilizador, opcionalmente filtrados por equipa. N\xE3o devolve dados pessoais sens\xEDveis de menores.",
  inputSchema: {
    team_id: z2.string().uuid().optional().describe("ID da equipa para filtrar."),
    only_active: z2.boolean().optional().describe("Se verdadeiro, devolve apenas jogadores ativos."),
    limit: z2.number().int().min(1).max(200).optional().describe("M\xE1ximo de jogadores (por omiss\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id, only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("players").select("id, name, number, position, secondary_positions, foot, status, is_active, team_id").order("number", { nullsFirst: false }).limit(limit ?? 100);
    if (team_id) query = query.eq("team_id", team_id);
    if (only_active) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-matches.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_matches_default = defineTool3({
  name: "list_matches",
  title: "Listar jogos",
  description: "Lista jogos (passados ou futuros) acess\xEDveis ao utilizador, com resultado e estado do relat\xF3rio.",
  inputSchema: {
    from_date: z3.string().optional().describe("Data m\xEDnima ISO (YYYY-MM-DD)."),
    to_date: z3.string().optional().describe("Data m\xE1xima ISO (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo de jogos (por omiss\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("matches").select("id, match_date, opponent_name, is_home, competition, goals_for, goals_against, status, report_status, location").eq("is_deleted", false).order("match_date", { ascending: false }).limit(limit ?? 25);
    if (from_date) query = query.gte("match_date", from_date);
    if (to_date) query = query.lte("match_date", to_date);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-trainings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_trainings_default = defineTool4({
  name: "list_trainings",
  title: "Listar treinos",
  description: "Lista sess\xF5es de treino acess\xEDveis ao utilizador, opcionalmente filtradas por equipa e intervalo de datas.",
  inputSchema: {
    team_id: z4.string().uuid().optional().describe("ID da equipa para filtrar."),
    from_date: z4.string().optional().describe("Data m\xEDnima ISO (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(100).optional().describe("M\xE1ximo de sess\xF5es (por omiss\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id, from_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("training_sessions").select("*").order("session_date", { ascending: false }).limit(limit ?? 25);
    if (team_id) query = query.eq("team_id", team_id);
    if (from_date) query = query.gte("session_date", from_date);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/get-match-report.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var get_match_report_default = defineTool5({
  name: "get_match_report",
  title: "Obter relat\xF3rio de jogo",
  description: "Devolve os detalhes de um jogo espec\xEDfico, incluindo titulares, banco, partes e minutos configurados.",
  inputSchema: {
    match_id: z5.string().uuid().describe("ID do jogo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: match, error } = await supabase.from("matches").select("*").eq("id", match_id).maybeSingle();
    if (error) return dbError(error.message);
    if (!match) return dbError("Jogo n\xE3o encontrado ou sem acesso.");
    const { data: events } = await supabase.from("match_events").select("*").eq("match_id", match_id).order("minute", { ascending: true });
    return jsonResult({ match, events: events ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "cxeoebdqbbckpcncpeqm";
var mcp_default = defineMcp({
  name: "tacticaflow-mcp",
  title: "TacticaFlow MCP",
  version: "0.1.0",
  instructions: "Ferramentas do TacticaFlow (gest\xE3o desportiva). Permite consultar equipas, jogadores, jogos, treinos e relat\xF3rios de jogo do utilizador autenticado. Todas as leituras respeitam as permiss\xF5es do clube/treinador.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_teams_default, list_players_default, list_matches_default, list_trainings_default, get_match_report_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
