import type { Drill } from './types';

const ALL_YOUTH = ['sub7', 'sub9', 'sub11'] as const;
const FROM_SUB11 = ['sub11', 'sub13', 'sub15', 'sub17', 'sub19', 'senior'] as const;
const FROM_SUB13 = ['sub13', 'sub15', 'sub17', 'sub19', 'senior'] as const;
const FROM_SUB15 = ['sub15', 'sub17', 'sub19', 'senior'] as const;

export const DRILLS: Drill[] = [
  // ─── AQUECIMENTO ─────────────────────────────────────────────────────────
  {
    id: 'apanhada-caudas',
    name: 'Apanhada das caudas',
    category: 'aquecimento',
    ages: [...ALL_YOUTH],
    players: { min: 6, max: 20 },
    minutes: 8,
    space: '20 × 20 m',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'media',
    objective: 'Ativar com bola, levantar a cabeça e proteger a bola de forma lúdica.',
    setup: 'Cada jogador conduz uma bola dentro do quadrado com um colete preso atrás no calção (a "cauda").',
    howTo: [
      'Todos conduzem a bola e tentam tirar caudas aos colegas sem perder a própria bola.',
      'Quem fica sem cauda continua a jogar e tenta recuperar uma.',
      'Rondas de 60–90 segundos; conta quem tem mais caudas no fim.',
    ],
    coachingPoints: ['Cabeça levantada para ver os colegas', 'Bola perto do pé', 'Usar o corpo entre o adversário e a bola'],
    progressions: ['Só pode conduzir com o pé menos hábil', 'Metade dos jogadores sem bola (caçadores)'],
    diagram: [
      { t: 'zone', at: [15, 8], w: 70, h: 48 },
      { t: 'a', at: [30, 20] }, { t: 'ball', at: [33, 22] }, { t: 'drive', from: [30, 20], to: [45, 26] },
      { t: 'a', at: [60, 18] }, { t: 'ball', at: [63, 20] }, { t: 'drive', from: [60, 18], to: [52, 32] },
      { t: 'd', at: [40, 42] }, { t: 'ball', at: [43, 44] }, { t: 'drive', from: [40, 42], to: [58, 44] },
      { t: 'd', at: [70, 40] }, { t: 'ball', at: [72, 42] },
      { t: 'a', at: [25, 45] }, { t: 'ball', at: [27, 47] },
      { t: 'cone', at: [15, 8] }, { t: 'cone', at: [85, 8] }, { t: 'cone', at: [15, 56] }, { t: 'cone', at: [85, 56] },
    ],
  },
  {
    id: 'semaforo',
    name: 'Semáforo com bola',
    category: 'aquecimento',
    ages: [...ALL_YOUTH],
    players: { min: 4, max: 20 },
    minutes: 8,
    space: '20 × 20 m',
    equipment: ['bolas', 'cones'],
    intensity: 'baixa',
    objective: 'Condução de bola com mudanças de ritmo e reação a sinais.',
    setup: 'Cada jogador com uma bola dentro do quadrado. O treinador tem três cores (ou diz as cores em voz alta).',
    howTo: [
      'Verde: conduzir rápido. Amarelo: conduzir devagar com a sola. Vermelho: parar a bola com a sola e sentar em cima.',
      'Acrescentar sinais: "roda" (roda com a bola), "troca" (troca de bola com um colega).',
    ],
    coachingPoints: ['Toques curtos e frequentes', 'Olhar para o treinador enquanto conduz', 'Usar as duas pernas'],
    progressions: ['Um jogador escolhido dá os sinais', 'Sinais só com gestos (obriga a levantar a cabeça)'],
    diagram: [
      { t: 'zone', at: [20, 8], w: 60, h: 48 },
      { t: 'a', at: [35, 22] }, { t: 'ball', at: [37, 24] }, { t: 'drive', from: [35, 22], to: [48, 18] },
      { t: 'a', at: [62, 30] }, { t: 'ball', at: [64, 32] }, { t: 'drive', from: [62, 30], to: [55, 44] },
      { t: 'a', at: [32, 44] }, { t: 'ball', at: [34, 46] }, { t: 'drive', from: [32, 44], to: [45, 38] },
      { t: 'n', at: [50, 60], n: 'T' },
    ],
  },
  {
    id: 'meinho-4x1',
    name: 'Meinho 4×1 (rondo)',
    category: 'aquecimento',
    ages: [...FROM_SUB11],
    players: { min: 5, max: 20 },
    minutes: 10,
    space: 'Quadrado de 8 × 8 a 10 × 10 m por grupo',
    equipment: ['bolas', 'cones'],
    intensity: 'media',
    objective: 'Passe rápido, receção orientada e ocupação dos apoios.',
    setup: 'Grupos de 5: quatro nos lados do quadrado, um no meio.',
    howTo: [
      'Os de fora trocam a bola, no máximo 2 toques; o do meio tenta intercetar.',
      'Quem perde a bola (ou a atira fora) vai ao meio.',
      'Contar passes seguidos: 10 passes = ponto.',
    ],
    coachingPoints: ['Apoio sempre à esquerda e à direita de quem tem a bola', 'Receber com o pé mais afastado do defensor', 'Passe tenso e rasteiro'],
    progressions: ['Só 1 toque', '5×2 em 12 × 12 m', 'Passe entre as pernas do meio vale 2 pontos'],
    diagram: [
      { t: 'zone', at: [30, 12], w: 40, h: 40 },
      { t: 'a', at: [50, 12] }, { t: 'a', at: [70, 32] }, { t: 'a', at: [50, 52] }, { t: 'a', at: [30, 32] },
      { t: 'd', at: [50, 32] }, { t: 'ball', at: [52, 14] },
      { t: 'pass', from: [50, 12], to: [70, 32] }, { t: 'pass', from: [70, 32], to: [50, 52] },
    ],
  },
  {
    id: 'ativacao-dinamica',
    name: 'Ativação dinâmica em corredor',
    category: 'aquecimento',
    ages: [...FROM_SUB13],
    players: { min: 2, max: 30 },
    minutes: 10,
    space: 'Corredor de 20 m',
    equipment: ['cones'],
    intensity: 'baixa',
    objective: 'Preparar articulações e músculos, prevenir lesões.',
    setup: 'Duas linhas de cones separadas 20 m. Jogadores em fila numa das linhas.',
    howTo: [
      'Ida e volta de cada exercício: corrida leve, skipping baixo, calcanhares ao glúteo, abrir e fechar a anca, passos laterais, afundos a andar.',
      'Terminar com 3 acelerações progressivas (60%, 80%, 95%).',
    ],
    coachingPoints: ['Postura alta, olhar em frente', 'Amplitude primeiro, velocidade depois', 'Nos afundos, joelho alinhado com o pé'],
    progressions: ['Juntar mudanças de direção nos últimos 5 m', 'Incluir bola nas acelerações'],
    diagram: [
      { t: 'cone', at: [15, 16] }, { t: 'cone', at: [15, 28] }, { t: 'cone', at: [15, 40] }, { t: 'cone', at: [15, 52] },
      { t: 'cone', at: [85, 16] }, { t: 'cone', at: [85, 28] }, { t: 'cone', at: [85, 40] }, { t: 'cone', at: [85, 52] },
      { t: 'a', at: [12, 16] }, { t: 'a', at: [12, 28] }, { t: 'a', at: [12, 40] }, { t: 'a', at: [12, 52] },
      { t: 'run', from: [18, 16], to: [82, 16] }, { t: 'run', from: [18, 28], to: [82, 28] },
      { t: 'text', at: [50, 8], text: '20 m' },
    ],
  },
  {
    id: 'circuito-passe-y',
    name: 'Circuito de passe em Y',
    category: 'passe',
    ages: [...FROM_SUB13],
    players: { min: 6, max: 14 },
    minutes: 12,
    space: '25 × 20 m',
    equipment: ['bolas', 'cones'],
    intensity: 'media',
    objective: 'Passe e receção com apoios frontais e jogo em terceiro homem.',
    setup: 'Cones em Y: um na base (A), um ao centro (B) e dois nas pontas (C e D). Jogadores distribuídos pelos cones, bolas na base.',
    howTo: [
      'A passa para B, que devolve de primeira (apoio frontal); A passa longo para C; C conduz e passa para D.',
      'Cada jogador segue o seu passe para o cone seguinte.',
      'Alternar lado direito e esquerdo a cada 3 minutos.',
    ],
    coachingPoints: ['Contra-movimento antes de pedir a bola', 'Receber orientado para o lado do jogo', 'Comunicar: "sim", "vira", "tempo"'],
    progressions: ['B em vez de devolver roda e joga para C (terceiro homem)', 'Limitar a 2 toques em todas as receções'],
    diagram: [
      { t: 'cone', at: [50, 58] }, { t: 'cone', at: [50, 34] }, { t: 'cone', at: [28, 10] }, { t: 'cone', at: [72, 10] },
      { t: 'a', at: [50, 55], n: 'A' }, { t: 'a', at: [50, 31], n: 'B' }, { t: 'a', at: [28, 13], n: 'C' }, { t: 'a', at: [72, 13], n: 'D' },
      { t: 'pass', from: [50, 53], to: [50, 34] }, { t: 'pass', from: [48, 33], to: [48, 52] },
      { t: 'pass', from: [50, 53], to: [30, 15] }, { t: 'drive', from: [28, 13], to: [45, 11] }, { t: 'pass', from: [45, 11], to: [70, 12] },
    ],
  },

  // ─── TÉCNICA ─────────────────────────────────────────────────────────────
  {
    id: 'piratas-tesouro',
    name: 'Piratas e o tesouro',
    category: 'tecnica',
    ages: ['sub7', 'sub9'],
    players: { min: 6, max: 16 },
    minutes: 10,
    space: '20 × 20 m',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'media',
    objective: 'Proteção de bola, condução e desarme de forma divertida.',
    setup: 'A maioria conduz uma bola (os "marinheiros"); 2 ou 3 "piratas" com colete, sem bola.',
    howTo: [
      'Os piratas tentam roubar as bolas e levá-las para o seu "barco" (quadrado de cones num canto).',
      'Marinheiro sem bola pode ir buscar uma ao barco dos piratas.',
      'Ronda de 2 minutos; trocar piratas.',
    ],
    coachingPoints: ['Pôr o corpo entre o pirata e a bola', 'Mudar de direção quando o pirata se aproxima', 'Os piratas atacam a bola, não o colega'],
    progressions: ['Mais piratas', 'Marinheiros só podem usar o pé esquerdo'],
    diagram: [
      { t: 'zone', at: [12, 8], w: 76, h: 48 },
      { t: 'zone', at: [74, 10], w: 12, h: 12, label: 'Barco' },
      { t: 'a', at: [30, 25] }, { t: 'ball', at: [32, 27] },
      { t: 'a', at: [45, 42] }, { t: 'ball', at: [47, 44] }, { t: 'drive', from: [45, 42], to: [30, 48] },
      { t: 'a', at: [58, 22] }, { t: 'ball', at: [60, 24] },
      { t: 'd', at: [40, 30] }, { t: 'run', from: [40, 30], to: [32, 27] },
      { t: 'd', at: [62, 40] }, { t: 'run', from: [62, 40], to: [48, 43] },
    ],
  },
  {
    id: 'drible-portas',
    name: '1×1 pelas portas',
    category: 'tecnica',
    ages: ['sub9', 'sub11', 'sub13'],
    players: { min: 4, max: 16 },
    minutes: 12,
    space: '20 × 25 m com 5–6 portas de cones (2 m)',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'alta',
    objective: 'Drible e finta para ultrapassar o adversário em 1×1.',
    setup: 'Pares dentro da área; uma bola por par. Várias portas de cones espalhadas.',
    howTo: [
      'Quem tem a bola ganha 1 ponto cada vez que a conduz através de uma porta.',
      'O defensor que recupera a bola passa a atacar.',
      'Não pode passar duas vezes seguidas na mesma porta.',
    ],
    coachingPoints: ['Fintar a um passo do defensor, não longe', 'Mudança de velocidade depois da finta', 'Defensor: aproximar rápido, travar e ficar de lado'],
    progressions: ['Portas valem pontos diferentes', '2×1 com um colega de apoio'],
    diagram: [
      { t: 'zone', at: [12, 6], w: 76, h: 52 },
      { t: 'cone', at: [28, 16] }, { t: 'cone', at: [28, 22] },
      { t: 'cone', at: [70, 14] }, { t: 'cone', at: [70, 20] },
      { t: 'cone', at: [48, 34] }, { t: 'cone', at: [48, 40] },
      { t: 'cone', at: [26, 46] }, { t: 'cone', at: [26, 52] },
      { t: 'a', at: [38, 38] }, { t: 'ball', at: [40, 39] }, { t: 'd', at: [44, 36] },
      { t: 'drive', from: [40, 39], to: [48, 37] },
      { t: 'a', at: [60, 20] }, { t: 'ball', at: [62, 21] }, { t: 'd', at: [66, 18] },
    ],
  },
  {
    id: 'estafetas-slalom',
    name: 'Estafetas em slalom',
    category: 'tecnica',
    ages: [...ALL_YOUTH],
    players: { min: 4, max: 20 },
    minutes: 10,
    space: '15 m por fila',
    equipment: ['bolas', 'cones'],
    intensity: 'media',
    objective: 'Condução com os dois pés e mudanças de direção curtas.',
    setup: 'Filas de 3–5 jogadores. À frente de cada fila, 5 cones em linha separados 1,5 m.',
    howTo: [
      'Conduzir em slalom até ao fim, contornar o último cone e voltar em linha reta.',
      'Entregar a bola ao próximo da fila com a sola.',
      'A fila que acabar primeiro ganha a ronda.',
    ],
    coachingPoints: ['Parte de dentro e de fora do pé', 'Toques curtos entre cones, longo na reta', 'Cabeça levanta na volta'],
    progressions: ['Só pé fraco', 'Na volta, remate a uma baliza pequena'],
    diagram: [
      { t: 'a', at: [10, 20] }, { t: 'ball', at: [13, 21] }, { t: 'a', at: [5, 20] },
      { t: 'cone', at: [25, 20] }, { t: 'cone', at: [35, 20] }, { t: 'cone', at: [45, 20] }, { t: 'cone', at: [55, 20] }, { t: 'cone', at: [65, 20] },
      { t: 'drive', from: [13, 21], to: [68, 20] },
      { t: 'd', at: [10, 44] }, { t: 'ball', at: [13, 45] }, { t: 'd', at: [5, 44] },
      { t: 'cone', at: [25, 44] }, { t: 'cone', at: [35, 44] }, { t: 'cone', at: [45, 44] }, { t: 'cone', at: [55, 44] }, { t: 'cone', at: [65, 44] },
    ],
  },
  {
    id: 'fintas-quadrado',
    name: 'Fintas no quadrado',
    category: 'tecnica',
    ages: ['sub9', 'sub11', 'sub13', 'sub15'],
    players: { min: 4, max: 20 },
    minutes: 10,
    space: '15 × 15 m',
    equipment: ['bolas', 'cones'],
    intensity: 'media',
    objective: 'Aprender e repetir fintas com qualidade antes de as usar em jogo.',
    setup: 'Cada jogador com uma bola; cones espalhados como "defensores".',
    howTo: [
      'Conduzir até um cone e executar a finta pedida pelo treinador (tesoura, finta de corpo, Cruyff, elástico simples).',
      '10 repetições por finta, depois escolha livre.',
    ],
    coachingPoints: ['Finta perto do cone', 'Sair rápido na direção contrária', 'Repetir com os dois pés'],
    progressions: ['Trocar cones por colegas que defendem a 50%', 'Terminar com remate'],
    diagram: [
      { t: 'zone', at: [22, 8], w: 56, h: 48 },
      { t: 'cone', at: [36, 22] }, { t: 'cone', at: [64, 22] }, { t: 'cone', at: [36, 44] }, { t: 'cone', at: [64, 44] }, { t: 'cone', at: [50, 33] },
      { t: 'a', at: [28, 30] }, { t: 'ball', at: [30, 31] }, { t: 'drive', from: [30, 31], to: [35, 24] }, { t: 'drive', from: [37, 23], to: [46, 16] },
      { t: 'a', at: [72, 38] }, { t: 'ball', at: [70, 39] },
    ],
  },
  {
    id: 'rececao-orientada-triangulo',
    name: 'Receção orientada em triângulo',
    category: 'passe',
    ages: [...FROM_SUB11],
    players: { min: 3, max: 18 },
    minutes: 10,
    space: 'Triângulo de 10 m de lado',
    equipment: ['bolas', 'cones'],
    intensity: 'baixa',
    objective: 'Receber já virado para o próximo passe, com o primeiro toque.',
    setup: 'Grupos de 3, um em cada cone do triângulo.',
    howTo: [
      'Passe sempre no mesmo sentido; cada jogador recebe com o pé mais afastado e passa ao seguinte em 2 toques.',
      'Ao fim de 2 minutos trocar o sentido.',
    ],
    coachingPoints: ['Abrir o corpo antes de a bola chegar', 'Primeiro toque para o espaço, não para os pés', 'Pé de apoio a apontar para onde vai passar'],
    progressions: ['1 toque', 'Um quarto jogador pressiona a 50% quem recebe'],
    diagram: [
      { t: 'cone', at: [50, 12] }, { t: 'cone', at: [28, 50] }, { t: 'cone', at: [72, 50] },
      { t: 'a', at: [50, 15] }, { t: 'a', at: [30, 47] }, { t: 'a', at: [70, 47] },
      { t: 'pass', from: [48, 17], to: [31, 45] }, { t: 'pass', from: [32, 48], to: [68, 48] }, { t: 'pass', from: [69, 45], to: [52, 17] },
    ],
  },

  // ─── PASSE ───────────────────────────────────────────────────────────────
  {
    id: 'quadrado-passe',
    name: 'Quadrado de passe e segue',
    category: 'passe',
    ages: [...FROM_SUB11],
    players: { min: 6, max: 16 },
    minutes: 10,
    space: '12 × 12 m',
    equipment: ['bolas', 'cones'],
    intensity: 'media',
    objective: 'Passe preciso, tempo de desmarcação e receção em movimento.',
    setup: 'Um jogador em cada canto (2 no canto de partida). Uma ou duas bolas.',
    howTo: [
      'Passa ao canto seguinte e corre para o lugar para onde passou.',
      'Mudar de sentido a cada 2 minutos; depois jogar com duas bolas em simultâneo.',
    ],
    coachingPoints: ['Pedir a bola com a mão e com a voz', 'Passe para o pé mais afastado do colega', 'Receção e passe no mesmo movimento'],
    progressions: ['Passe em diagonal e sobreposição', 'Tabela (1-2) antes de seguir'],
    diagram: [
      { t: 'cone', at: [30, 12] }, { t: 'cone', at: [70, 12] }, { t: 'cone', at: [70, 52] }, { t: 'cone', at: [30, 52] },
      { t: 'a', at: [30, 15] }, { t: 'a', at: [67, 12] }, { t: 'a', at: [70, 49] }, { t: 'a', at: [33, 52] }, { t: 'a', at: [26, 15] },
      { t: 'ball', at: [33, 16] },
      { t: 'pass', from: [33, 15], to: [65, 13] }, { t: 'run', from: [30, 18], to: [64, 18] },
    ],
  },
  {
    id: 'passe-segue-linhas',
    name: 'Passe em linhas',
    category: 'passe',
    ages: ['sub9', 'sub11', 'sub13'],
    players: { min: 4, max: 20 },
    minutes: 8,
    space: 'Duas filas frente a frente a 8–12 m',
    equipment: ['bolas', 'cones'],
    intensity: 'baixa',
    objective: 'Técnica de passe com a parte de dentro do pé e receção.',
    setup: 'Duas filas uma em frente à outra; bola na fila A.',
    howTo: [
      'Passa ao primeiro da fila da frente e corre para o fim dessa fila.',
      'Receção com um pé, passe com o outro.',
    ],
    coachingPoints: ['Pé de apoio ao lado da bola', 'Tornozelo firme, bater no meio da bola', 'Acompanhar o passe com a perna'],
    progressions: ['Aumentar a distância', 'Passe de primeira', 'Cone no meio: o passe tem de o contornar em curva'],
    diagram: [
      { t: 'a', at: [20, 32] }, { t: 'a', at: [14, 32] }, { t: 'a', at: [8, 32] },
      { t: 'a', at: [80, 32] }, { t: 'a', at: [86, 32] }, { t: 'a', at: [92, 32] },
      { t: 'ball', at: [23, 33] },
      { t: 'pass', from: [23, 33], to: [77, 33] }, { t: 'run', from: [20, 28], to: [90, 26] },
    ],
  },
  {
    id: 'tabela-remate',
    name: 'Tabela e remate',
    category: 'finalizacao',
    ages: [...FROM_SUB11],
    players: { min: 4, max: 14 },
    minutes: 12,
    space: 'Meio-campo com baliza',
    equipment: ['bolas', 'cones', 'balizas'],
    intensity: 'media',
    objective: 'Combinação 1-2 (tabela) seguida de finalização.',
    setup: 'Fila de atacantes a 25 m da baliza; um apoio (fixo) à entrada da área; GR na baliza.',
    howTo: [
      'Atacante conduz, passa ao apoio, desmarca-se e recebe a devolução de primeira.',
      'Remata em 1 ou 2 toques. Rodar: atacante → apoio → fila.',
    ],
    coachingPoints: ['Passe firme ao apoio', 'Arrancar logo depois de passar', 'Olhar para o GR antes de rematar'],
    progressions: ['Defensor passivo junto ao apoio', 'Remate só de primeira'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' },
      { t: 'gk', at: [50, 4] },
      { t: 'line', from: [30, 0], to: [30, 18] }, { t: 'line', from: [30, 18], to: [70, 18] }, { t: 'line', from: [70, 18], to: [70, 0] },
      { t: 'a', at: [40, 26], n: 'F' },
      { t: 'a', at: [55, 56] }, { t: 'a', at: [55, 61] }, { t: 'ball', at: [57, 53] },
      { t: 'drive', from: [55, 53], to: [55, 42] }, { t: 'pass', from: [55, 42], to: [42, 28] },
      { t: 'run', from: [57, 40], to: [57, 24] }, { t: 'pass', from: [42, 26], to: [56, 23] },
      { t: 'shot', from: [57, 22], to: [52, 2] },
    ],
  },

  // ─── FINALIZAÇÃO ─────────────────────────────────────────────────────────
  {
    id: 'conducao-remate',
    name: 'Condução e remate',
    category: 'finalizacao',
    ages: ['sub9', 'sub11', 'sub13', 'sub15'],
    players: { min: 3, max: 16 },
    minutes: 10,
    space: '30 m até à baliza',
    equipment: ['bolas', 'cones', 'balizas'],
    intensity: 'media',
    objective: 'Rematar em movimento depois de conduzir, com precisão.',
    setup: 'Duas filas afastadas 15 m, cada uma com um cone a contornar antes do remate.',
    howTo: [
      'Conduzir rápido, contornar o cone e rematar antes da linha da área.',
      'Alternar as filas; a fila da direita remata com o pé esquerdo e vice-versa.',
    ],
    coachingPoints: ['Último toque a preparar o remate', 'Corpo por cima da bola (remate rasteiro)', 'Apontar aos cantos'],
    progressions: ['Defensor a perseguir a partir de trás', 'Remate de primeira depois de passe do treinador'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'a', at: [30, 58] }, { t: 'a', at: [70, 58] }, { t: 'ball', at: [32, 55] },
      { t: 'cone', at: [36, 34] }, { t: 'cone', at: [64, 34] },
      { t: 'drive', from: [32, 55], to: [38, 36] }, { t: 'drive', from: [38, 34], to: [44, 24] }, { t: 'shot', from: [44, 22], to: [54, 2] },
    ],
  },
  {
    id: '2x1-finalizacao',
    name: '2×1 com finalização',
    category: 'finalizacao',
    ages: [...FROM_SUB11],
    players: { min: 6, max: 16 },
    minutes: 15,
    space: '30 × 25 m com baliza',
    equipment: ['bolas', 'cones', 'coletes', 'balizas'],
    intensity: 'alta',
    objective: 'Decidir entre passar e conduzir em superioridade numérica.',
    setup: 'Dois atacantes contra um defensor que parte da linha da área; GR na baliza.',
    howTo: [
      'Os atacantes têm 8 segundos para finalizar.',
      'Se o defensor recuperar, marca ponto conduzindo a bola para trás da linha de partida.',
    ],
    coachingPoints: ['Conduzir para o defensor para o fixar', 'Passar quando ele se compromete', 'O companheiro dá largura e profundidade'],
    progressions: ['3×2', 'Segundo defensor entra 3 segundos depois'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'd', at: [50, 22] },
      { t: 'a', at: [44, 50] }, { t: 'ball', at: [46, 48] }, { t: 'a', at: [66, 50] },
      { t: 'drive', from: [46, 48], to: [48, 32] }, { t: 'run', from: [66, 50], to: [64, 22] },
      { t: 'pass', from: [48, 30], to: [62, 22] }, { t: 'shot', from: [64, 20], to: [54, 2] },
    ],
  },
  {
    id: 'cruzamento-finalizacao',
    name: 'Cruzamento e finalização',
    category: 'finalizacao',
    ages: [...FROM_SUB13],
    players: { min: 6, max: 16 },
    minutes: 15,
    space: 'Meio-campo',
    equipment: ['bolas', 'cones', 'balizas'],
    intensity: 'media',
    objective: 'Ataque à área: 1.º poste, 2.º poste e entrada da área.',
    setup: 'Extremos nos corredores com bolas; três finalizadores ao centro; GR.',
    howTo: [
      'Extremo conduz até à linha e cruza; os três atacam os espaços: 1.º poste, 2.º poste e marca de penálti.',
      'Alternar corredor direito e esquerdo.',
    ],
    coachingPoints: ['Chegar à área no momento do cruzamento, não antes', 'Cruzamento tenso entre GR e defesa', 'Finalizar ao chão ou de cabeça para baixo'],
    progressions: ['Juntar 2 defensores', 'Cruzamento atrasado (cutback) à entrada da área'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'line', from: [26, 0], to: [26, 20] }, { t: 'line', from: [26, 20], to: [74, 20] }, { t: 'line', from: [74, 20], to: [74, 0] },
      { t: 'a', at: [88, 34] }, { t: 'ball', at: [90, 32] }, { t: 'drive', from: [90, 32], to: [92, 10] },
      { t: 'pass', from: [91, 8], to: [60, 10] },
      { t: 'a', at: [45, 36] }, { t: 'run', from: [45, 34], to: [58, 10] },
      { t: 'a', at: [55, 40] }, { t: 'run', from: [55, 38], to: [40, 12] },
      { t: 'a', at: [50, 46] }, { t: 'run', from: [50, 44], to: [50, 24] },
    ],
  },
  {
    id: 'rodar-rematar',
    name: 'Rodar e rematar',
    category: 'finalizacao',
    ages: [...FROM_SUB13],
    players: { min: 4, max: 12 },
    minutes: 12,
    space: 'Entrada da área',
    equipment: ['bolas', 'cones', 'balizas', 'coletes'],
    intensity: 'alta',
    objective: 'Receber de costas para a baliza, rodar e finalizar rápido.',
    setup: 'Avançado à entrada da área de costas para a baliza, defensor atrás dele; passes vindos do meio-campo.',
    howTo: [
      'O passador joga no avançado, que tem 3 toques para rodar e rematar.',
      'Defensor começa passivo, depois ativo.',
    ],
    coachingPoints: ['Olhar por cima do ombro antes da bola chegar', 'Sentir o defensor com o braço', 'Rodar para o lado contrário ao defensor'],
    progressions: ['Apoio de um médio para tabela', 'Remate em 2 toques'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'd', at: [50, 20] }, { t: 'a', at: [50, 26], n: '9' },
      { t: 'a', at: [50, 56] }, { t: 'ball', at: [52, 54] },
      { t: 'pass', from: [50, 53], to: [50, 29] }, { t: 'drive', from: [52, 25], to: [60, 18] }, { t: 'shot', from: [60, 16], to: [54, 2] },
    ],
  },

  // ─── POSSE ───────────────────────────────────────────────────────────────
  {
    id: 'rondo-5x2',
    name: 'Rondo 5×2',
    category: 'posse',
    ages: [...FROM_SUB13],
    players: { min: 7, max: 21 },
    minutes: 12,
    space: '14 × 14 m por grupo',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'media',
    objective: 'Circulação rápida, passe que "tira" os dois defensores, reação à perda.',
    setup: 'Cinco à volta (um pode entrar no meio), dois defensores no centro.',
    howTo: [
      'Máximo 2 toques. Passe entre os dois defensores vale ponto.',
      'Quem perde a bola troca com o defensor que está há mais tempo no meio.',
    ],
    coachingPoints: ['Ângulos de passe: não ficar atrás de um defensor', 'Jogar para quem está livre, não para quem pede mais alto', 'Defensores pressionam em dupla: um à bola, outro fecha o passe interior'],
    progressions: ['1 toque', 'Ao recuperar, os defensores têm de passar a bola para fora do quadrado'],
    diagram: [
      { t: 'zone', at: [28, 10], w: 44, h: 44 },
      { t: 'a', at: [28, 20] }, { t: 'a', at: [50, 10] }, { t: 'a', at: [72, 26] }, { t: 'a', at: [62, 54] }, { t: 'a', at: [34, 50] },
      { t: 'd', at: [46, 30] }, { t: 'd', at: [56, 38] },
      { t: 'ball', at: [30, 22] }, { t: 'pass', from: [30, 22], to: [70, 26] }, { t: 'pass', from: [70, 28], to: [36, 48] },
    ],
  },
  {
    id: 'posse-4x4-jokers',
    name: 'Posse 4×4 + 3 jokers',
    category: 'posse',
    ages: [...FROM_SUB13],
    players: { min: 11, max: 11 },
    minutes: 15,
    space: '25 × 25 m',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'alta',
    objective: 'Manter a bola em superioridade, largura e apoios.',
    setup: 'Duas equipas de 4 e três jokers (um em cada lado lateral e um no meio) que jogam sempre com quem tem a bola.',
    howTo: [
      '8 passes seguidos = ponto. Jokers com 1 ou 2 toques.',
      'Séries de 3 minutos com 1 minuto de descanso; trocar os jokers.',
    ],
    coachingPoints: ['Abrir o campo: usar os jokers das laterais', 'Mudar o centro de jogo quando o lado está fechado', 'Pressão imediata quando se perde a bola'],
    progressions: ['Jokers só de 1 toque', 'Ponto extra se o passe atravessa a zona central'],
    diagram: [
      { t: 'zone', at: [16, 6], w: 68, h: 52 },
      { t: 'n', at: [16, 32] }, { t: 'n', at: [84, 32] }, { t: 'n', at: [50, 32] },
      { t: 'a', at: [30, 16] }, { t: 'a', at: [66, 14] }, { t: 'a', at: [34, 48] }, { t: 'a', at: [68, 48] },
      { t: 'd', at: [42, 22] }, { t: 'd', at: [58, 24] }, { t: 'd', at: [44, 42] }, { t: 'd', at: [60, 40] },
      { t: 'ball', at: [32, 18] }, { t: 'pass', from: [32, 18], to: [18, 30] }, { t: 'pass', from: [18, 34], to: [34, 46] },
    ],
  },
  {
    id: 'jogo-das-portas',
    name: 'Jogo das portas',
    category: 'posse',
    ages: ['sub9', 'sub11', 'sub13', 'sub15'],
    players: { min: 6, max: 16 },
    minutes: 12,
    space: '30 × 25 m com 5 portas',
    equipment: ['bolas', 'cones', 'coletes'],
    intensity: 'alta',
    objective: 'Passe e desmarcação: jogar para o espaço do colega.',
    setup: 'Duas equipas; portas de cones de 2 m espalhadas.',
    howTo: [
      'Ponto quando um passe atravessa uma porta e é recebido por um colega do outro lado.',
      'Não se pode marcar duas vezes seguidas na mesma porta.',
    ],
    coachingPoints: ['Desmarcar para o lado da porta livre', 'Passe no tempo certo, não tarde', 'Defender a porta mais próxima da bola'],
    progressions: ['Portas só valem se o passe for de primeira', 'Reduzir para 3 portas'],
    diagram: [
      { t: 'zone', at: [8, 6], w: 84, h: 52 },
      { t: 'cone', at: [28, 16] }, { t: 'cone', at: [28, 22] },
      { t: 'cone', at: [72, 14] }, { t: 'cone', at: [72, 20] },
      { t: 'cone', at: [50, 30] }, { t: 'cone', at: [50, 36] },
      { t: 'cone', at: [26, 44] }, { t: 'cone', at: [26, 50] },
      { t: 'cone', at: [74, 44] }, { t: 'cone', at: [74, 50] },
      { t: 'a', at: [40, 33] }, { t: 'ball', at: [42, 34] }, { t: 'a', at: [60, 34] },
      { t: 'pass', from: [42, 34], to: [58, 33] }, { t: 'd', at: [48, 26] },
    ],
  },

  // ─── DEFESA ──────────────────────────────────────────────────────────────
  {
    id: '1x1-defensivo-corredor',
    name: '1×1 defensivo em corredor',
    category: 'defesa',
    ages: ['sub9', 'sub11', 'sub13', 'sub15', 'sub17', 'sub19', 'senior'],
    players: { min: 4, max: 16 },
    minutes: 12,
    space: 'Corredor de 10 × 20 m',
    equipment: ['bolas', 'cones', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Aproximação, travagem e desarme sem fazer falta.',
    setup: 'Defensor passa a bola ao atacante na outra ponta do corredor e sai a defender. Baliza pequena atrás do defensor.',
    howTo: [
      'O atacante tenta marcar na baliza pequena; o defensor, se recuperar, conduz até à linha do atacante.',
      'Rodar papéis a cada repetição.',
    ],
    coachingPoints: ['Correr rápido e travar a 2 m', 'Posição de lado, joelhos fletidos', 'Orientar o atacante para fora / para o pé fraco', 'Paciência: atacar a bola no toque longo'],
    progressions: ['Corredor mais largo (mais difícil defender)', 'Ajuda de um segundo defensor após 3 s'],
    diagram: [
      { t: 'zone', at: [30, 4], w: 40, h: 56 },
      { t: 'goal', at: [50, 60], side: 'bottom', small: true },
      { t: 'd', at: [50, 52] }, { t: 'a', at: [50, 8] }, { t: 'ball', at: [50, 12] },
      { t: 'run', from: [50, 50], to: [50, 26] }, { t: 'drive', from: [50, 12], to: [58, 24] },
    ],
  },
  {
    id: '2x2-coberturas',
    name: '2×2 com coberturas',
    category: 'defesa',
    ages: [...FROM_SUB13],
    players: { min: 8, max: 16 },
    minutes: 15,
    space: '20 × 25 m, duas balizas pequenas',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Primeiro defensor pressiona, segundo faz cobertura; comunicação.',
    setup: 'Dois atacantes contra dois defensores; filas de espera nos cantos.',
    howTo: [
      'Os atacantes marcam nas duas balizas pequenas da linha de fundo; se os defensores recuperam, contra-atacam para a linha de meio-campo.',
      'Jogadas de 20 segundos.',
    ],
    coachingPoints: ['Quem está mais perto da bola pressiona', 'O outro fica em diagonal, 2–3 m atrás', 'Comunicar: "vou", "cobre", "troca"'],
    progressions: ['3×3', 'Defensores só podem ganhar ponto com recuperação limpa'],
    diagram: [
      { t: 'zone', at: [22, 4], w: 56, h: 56 },
      { t: 'goal', at: [36, 60], side: 'bottom', small: true }, { t: 'goal', at: [64, 60], side: 'bottom', small: true },
      { t: 'a', at: [40, 18] }, { t: 'ball', at: [42, 20] }, { t: 'a', at: [62, 20] },
      { t: 'd', at: [44, 30] }, { t: 'd', at: [54, 38] },
      { t: 'run', from: [44, 30], to: [43, 23] },
    ],
  },
  {
    id: 'linha-4-basculacao',
    name: 'Linha de 4 — basculação',
    category: 'defesa',
    ages: [...FROM_SUB15],
    players: { min: 8, max: 14 },
    minutes: 15,
    space: 'Meio-campo',
    equipment: ['bolas', 'cones', 'coletes', 'balizas'],
    intensity: 'media',
    objective: 'Deslocamentos coletivos da defesa conforme a posição da bola.',
    setup: 'Quatro defensores + GR contra 4–6 atacantes que circulam a bola à frente da área.',
    howTo: [
      'Fase 1 (sem oposição real): atacantes trocam a bola devagar; a linha desliza, fecha e sobe/desce ao sinal.',
      'Fase 2: atacantes podem finalizar; defesa ganha ponto ao recuperar e passar para um mini-alvo.',
    ],
    coachingPoints: ['Distância entre defesas de 8–10 m', 'Lateral do lado contrário fecha por dentro', 'Subir quando a bola está pressionada, descer quando está livre'],
    progressions: ['Juntar um médio defensivo à frente da linha', 'Atacantes com liberdade total'],
    diagram: [
      { t: 'goal', at: [50, 64], side: 'bottom' }, { t: 'gk', at: [50, 60] },
      { t: 'd', at: [26, 44] }, { t: 'd', at: [42, 46] }, { t: 'd', at: [58, 46] }, { t: 'd', at: [74, 44] },
      { t: 'a', at: [20, 24] }, { t: 'ball', at: [22, 26] }, { t: 'a', at: [40, 20] }, { t: 'a', at: [60, 20] }, { t: 'a', at: [80, 24] },
      { t: 'run', from: [74, 44], to: [64, 46] }, { t: 'run', from: [26, 44], to: [22, 38] },
    ],
  },

  // ─── TRANSIÇÃO ───────────────────────────────────────────────────────────
  {
    id: 'quem-marca-fica',
    name: 'Quem marca fica (3 equipas)',
    category: 'transicao',
    ages: [...FROM_SUB11],
    players: { min: 9, max: 15 },
    minutes: 15,
    space: '30 × 20 m, duas balizas',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Reação rápida ao ganhar e ao perder a bola.',
    setup: 'Três equipas de 3–5. Duas jogam, a terceira espera atrás de uma baliza.',
    howTo: [
      'Jogo rápido: quem marca fica e defende a baliza contrária; quem sofre sai e a equipa em espera entra logo a atacar.',
      'Não há paragens: a bola seguinte entra imediatamente.',
    ],
    coachingPoints: ['Ao perder: pressão imediata ao portador', 'Ao ganhar: primeiro olhar é para a frente', 'A equipa que entra está pronta e organizada'],
    progressions: ['Golo em menos de 10 s depois de recuperar vale 2', 'Campo mais comprido'],
    diagram: [
      { t: 'zone', at: [10, 12], w: 80, h: 40 },
      { t: 'goal', at: [10, 32], side: 'left', small: true }, { t: 'goal', at: [90, 32], side: 'right', small: true },
      { t: 'a', at: [34, 22] }, { t: 'a', at: [40, 40] }, { t: 'a', at: [52, 30] }, { t: 'ball', at: [54, 31] },
      { t: 'd', at: [62, 22] }, { t: 'd', at: [66, 38] }, { t: 'd', at: [74, 30] },
      { t: 'n', at: [97, 20], n: 'C' }, { t: 'n', at: [97, 44], n: 'C' },
      { t: 'drive', from: [54, 31], to: [70, 30] },
    ],
  },
  {
    id: 'contra-ataque-3x2-ondas',
    name: 'Contra-ataque 3×2 em ondas',
    category: 'transicao',
    ages: [...FROM_SUB13],
    players: { min: 10, max: 18 },
    minutes: 15,
    space: 'Campo de 40 × 30 m com duas balizas',
    equipment: ['bolas', 'cones', 'coletes', 'balizas'],
    intensity: 'alta',
    objective: 'Contra-atacar em superioridade e reorganizar rápido.',
    setup: 'Três atacam contra dois defensores numa baliza; depois os dois defensores + 1 da fila atacam a outra baliza.',
    howTo: [
      'Ataque 3×2 com limite de 8 segundos.',
      'Ao terminar (golo, fora ou recuperação) a onda contrária sai logo.',
    ],
    coachingPoints: ['Portador no corredor central', 'Extremos largos e em profundidade', 'Defensores atrasam: não se atiram ao portador'],
    progressions: ['Defensor extra recupera de trás', '4×3'],
    diagram: [
      { t: 'goal', at: [0, 32], side: 'left' }, { t: 'goal', at: [100, 32], side: 'right' },
      { t: 'gk', at: [3, 32] }, { t: 'gk', at: [97, 32] },
      { t: 'line', from: [50, 0], to: [50, 64] },
      { t: 'a', at: [40, 32] }, { t: 'ball', at: [42, 33] }, { t: 'a', at: [40, 14] }, { t: 'a', at: [40, 50] },
      { t: 'd', at: [72, 26] }, { t: 'd', at: [72, 40] },
      { t: 'drive', from: [42, 33], to: [60, 32] }, { t: 'run', from: [40, 14], to: [78, 18] }, { t: 'run', from: [40, 50], to: [78, 46] },
    ],
  },
  {
    id: 'pressao-5-segundos',
    name: 'Pressão dos 5 segundos',
    category: 'transicao',
    ages: [...FROM_SUB15],
    players: { min: 10, max: 16 },
    minutes: 15,
    space: '35 × 30 m',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Recuperar a bola logo após a perda (contra-pressão).',
    setup: 'Jogo 5×5 (+GR opcionais) com balizas pequenas.',
    howTo: [
      'Se uma equipa recupera a bola até 5 segundos depois de a perder, ganha 1 ponto (além dos golos).',
      'O treinador conta em voz alta os 5 segundos.',
    ],
    coachingPoints: ['Os 2–3 mais perto da bola pressionam logo', 'Fechar as linhas de passe fáceis', 'Se não recuperar em 5 s, reorganizar atrás da bola'],
    progressions: ['Golo depois de recuperação na contra-pressão vale 3', 'Campo maior'],
    diagram: [
      { t: 'zone', at: [10, 8], w: 80, h: 48 },
      { t: 'goal', at: [10, 32], side: 'left', small: true }, { t: 'goal', at: [90, 32], side: 'right', small: true },
      { t: 'd', at: [52, 30] }, { t: 'ball', at: [54, 31] },
      { t: 'a', at: [48, 22] }, { t: 'a', at: [60, 40] }, { t: 'a', at: [44, 38] },
      { t: 'run', from: [48, 22], to: [52, 28] }, { t: 'run', from: [60, 40], to: [56, 33] }, { t: 'run', from: [44, 38], to: [48, 34] },
      { t: 'text', at: [50, 14], text: '5 s' },
    ],
  },

  // ─── JOGO REDUZIDO ───────────────────────────────────────────────────────
  {
    id: '3x3-quatro-balizas',
    name: '3×3 com quatro balizas',
    category: 'jogo',
    ages: ['sub7', 'sub9', 'sub11', 'sub13'],
    players: { min: 6, max: 6 },
    minutes: 12,
    space: '25 × 20 m, duas balizas pequenas em cada linha de fundo',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Muitos toques, decisões e golos: ver onde está o espaço livre.',
    setup: 'Duas equipas de 3; cada equipa ataca duas balizas pequenas (ou portas de cones).',
    howTo: [
      'Jogo livre; sem guarda-redes; golo só dentro da zona de finalização (últimos 6 m).',
      'Bolas de reserva à volta: quando uma sai, entra logo outra.',
    ],
    coachingPoints: ['Atacar a baliza que o adversário deixou aberta', 'Largura: um colega de cada lado', 'Todos defendem, todos atacam'],
    progressions: ['4×4', 'Golo só depois de todos tocarem na bola'],
    diagram: [
      { t: 'zone', at: [10, 10], w: 80, h: 44 },
      { t: 'goal', at: [10, 20], side: 'left', small: true }, { t: 'goal', at: [10, 44], side: 'left', small: true },
      { t: 'goal', at: [90, 20], side: 'right', small: true }, { t: 'goal', at: [90, 44], side: 'right', small: true },
      { t: 'a', at: [40, 20] }, { t: 'a', at: [48, 42] }, { t: 'a', at: [60, 30] }, { t: 'ball', at: [62, 31] },
      { t: 'd', at: [66, 22] }, { t: 'd', at: [70, 38] }, { t: 'd', at: [52, 30] },
      { t: 'drive', from: [62, 31], to: [76, 40] }, { t: 'shot', from: [78, 42], to: [89, 44] },
    ],
  },
  {
    id: 'jogo-7x7-zonas',
    name: 'Jogo 7×7 por zonas',
    category: 'jogo',
    ages: [...FROM_SUB13],
    players: { min: 12, max: 16 },
    minutes: 25,
    space: 'Meio-campo, dividido em 3 zonas',
    equipment: ['bolas', 'cones', 'coletes', 'balizas'],
    intensity: 'alta',
    objective: 'Jogo formal com uma regra que puxa o tema do treino.',
    setup: 'Duas equipas de 6 + GR. Campo dividido em zona defensiva, média e ofensiva.',
    howTo: [
      'Escolher UMA condição conforme o tema: construção (sair a jogar pela zona defensiva), largura (golo depois de cruzamento vale 2), pressão (recuperar na zona ofensiva vale 1).',
      '2–3 blocos de 7 minutos com 2 minutos de descanso.',
    ],
    coachingPoints: ['Parar pouco: corrigir no momento e deixar jogar', 'Reforçar em voz alta o que foi treinado no exercício anterior'],
    progressions: ['Sem condição no último bloco (jogo livre)'],
    diagram: [
      { t: 'goal', at: [0, 32], side: 'left' }, { t: 'goal', at: [100, 32], side: 'right' },
      { t: 'gk', at: [3, 32] }, { t: 'gk', at: [97, 32] },
      { t: 'line', from: [33, 0], to: [33, 64] }, { t: 'line', from: [66, 0], to: [66, 64] },
      { t: 'a', at: [20, 16] }, { t: 'a', at: [20, 48] }, { t: 'a', at: [45, 22] }, { t: 'a', at: [45, 44] }, { t: 'a', at: [60, 32] }, { t: 'a', at: [78, 30] },
      { t: 'd', at: [80, 16] }, { t: 'd', at: [80, 48] }, { t: 'd', at: [55, 20] }, { t: 'd', at: [55, 44] }, { t: 'd', at: [40, 32] }, { t: 'd', at: [24, 32] },
      { t: 'text', at: [16, 6], text: 'Defensiva' }, { t: 'text', at: [50, 6], text: 'Média' }, { t: 'text', at: [83, 6], text: 'Ofensiva' },
    ],
  },
  {
    id: 'festival-4x4',
    name: 'Festival 4×4 (vários campos)',
    category: 'jogo',
    ages: ['sub7', 'sub9', 'sub11'],
    players: { min: 8, max: 24 },
    minutes: 20,
    space: '2 ou 3 minicampos de 25 × 20 m',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Todos jogam muito tempo: é o melhor treino para os mais novos.',
    setup: 'Vários minicampos lado a lado; equipas de 3 ou 4 sem guarda-redes fixo.',
    howTo: [
      'Jogos de 4 minutos; no fim, a equipa que ganhou sobe de campo e a que perdeu desce.',
      'Sem banco: todos jogam sempre.',
    ],
    coachingPoints: ['Elogiar tentativas de drible e de remate', 'Poucas instruções durante o jogo', 'Rodar quem vai à baliza'],
    progressions: ['Regras diferentes em cada campo (só pé fraco, golo de primeira vale 2)'],
    diagram: [
      { t: 'zone', at: [2, 4], w: 46, h: 56 }, { t: 'zone', at: [52, 4], w: 46, h: 56 },
      { t: 'goal', at: [25, 4], side: 'top', small: true }, { t: 'goal', at: [25, 60], side: 'bottom', small: true },
      { t: 'goal', at: [75, 4], side: 'top', small: true }, { t: 'goal', at: [75, 60], side: 'bottom', small: true },
      { t: 'a', at: [18, 36] }, { t: 'a', at: [32, 44] }, { t: 'd', at: [20, 22] }, { t: 'd', at: [30, 18] }, { t: 'ball', at: [20, 34] },
      { t: 'a', at: [68, 26] }, { t: 'a', at: [84, 30] }, { t: 'd', at: [70, 42] }, { t: 'd', at: [82, 46] }, { t: 'ball', at: [70, 28] },
    ],
  },

  // ─── GUARDA-REDES ────────────────────────────────────────────────────────
  {
    id: 'gr-posicao-encaixe',
    name: 'GR: posição base e encaixe',
    category: 'guarda_redes',
    ages: [...FROM_SUB11],
    players: { min: 2, max: 4 },
    minutes: 12,
    space: 'Baliza e área',
    equipment: ['bolas', 'cones', 'balizas'],
    intensity: 'media',
    objective: 'Posição de expectativa e agarrar a bola com segurança.',
    setup: 'GR na baliza; treinador ou colega remata/lança de 8–12 m.',
    howTo: [
      'Séries de 8 bolas: rasteiras ao corpo, meia altura e altura do peito.',
      'Depois de cada defesa, rolar a bola ao treinador e voltar à posição base.',
    ],
    coachingPoints: ['Pés à largura dos ombros, peso na frente dos pés', 'Mãos em "W" para bolas altas, em concha para baixas', 'Trazer a bola ao peito'],
    progressions: ['Remates de ângulos diferentes', 'Encaixe depois de um salto lateral'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 5] },
      { t: 'cone', at: [40, 20] }, { t: 'cone', at: [60, 20] },
      { t: 'n', at: [50, 32], n: 'T' }, { t: 'ball', at: [50, 29] },
      { t: 'shot', from: [50, 29], to: [50, 7] },
    ],
  },
  {
    id: 'gr-saidas-1x1',
    name: 'GR: saídas ao 1×1',
    category: 'guarda_redes',
    ages: [...FROM_SUB13],
    players: { min: 3, max: 8 },
    minutes: 12,
    space: 'Área e entrada da área',
    equipment: ['bolas', 'cones', 'balizas'],
    intensity: 'alta',
    objective: 'Reduzir o ângulo e ganhar o 1×1 ao avançado isolado.',
    setup: 'Avançados partem de 25 m em condução; GR na baliza.',
    howTo: [
      'O avançado tenta finalizar; o GR sai quando o avançado dá um toque mais longo.',
      'Repetições alternadas de ângulos (centro, esquerda, direita).',
    ],
    coachingPoints: ['Sair rápido e travar antes do remate', 'Ficar grande (braços abertos, baixo)', 'Não se atirar cedo: esperar a decisão do avançado'],
    progressions: ['Avançado com apoio de um colega (2×GR)'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 5] },
      { t: 'run', from: [50, 7], to: [50, 18] },
      { t: 'a', at: [50, 46] }, { t: 'ball', at: [50, 42] }, { t: 'drive', from: [50, 42], to: [50, 26] },
    ],
  },
  {
    id: 'gr-jogo-pes',
    name: 'GR: jogo de pés e distribuição',
    category: 'guarda_redes',
    ages: [...FROM_SUB13],
    players: { min: 3, max: 8 },
    minutes: 12,
    space: 'Meio-campo defensivo',
    equipment: ['bolas', 'cones', 'balizas', 'coletes'],
    intensity: 'media',
    objective: 'Receber passes atrasados e iniciar a construção.',
    setup: 'GR na baliza, dois defesas (centrais) abertos, um pressionante.',
    howTo: [
      'O central atrasa ao GR; o pressionante corre para o GR; o GR joga no central livre ou lança o lateral.',
      'Variante: pontapé de baliza curto ou longo conforme a pressão.',
    ],
    coachingPoints: ['Abrir o corpo para ver o campo', 'Primeiro toque para o lado contrário ao pressionante', 'Passe firme e rasteiro'],
    progressions: ['Dois pressionantes', 'Limite de 2 toques'],
    diagram: [
      { t: 'goal', at: [50, 64], side: 'bottom' }, { t: 'gk', at: [50, 58] },
      { t: 'a', at: [28, 50] }, { t: 'a', at: [72, 50] }, { t: 'd', at: [56, 38] },
      { t: 'pass', from: [30, 49], to: [48, 57] }, { t: 'run', from: [56, 38], to: [52, 52] }, { t: 'pass', from: [52, 57], to: [70, 51] },
    ],
  },

  // ─── COORDENAÇÃO E FÍSICO ────────────────────────────────────────────────
  {
    id: 'coordenacao-animais',
    name: 'Coordenação: o jardim zoológico',
    category: 'fisico',
    ages: [...ALL_YOUTH],
    players: { min: 4, max: 24 },
    minutes: 8,
    space: 'Qualquer espaço de 15 m',
    equipment: ['cones'],
    intensity: 'media',
    objective: 'Coordenação, equilíbrio e agilidade sem material nenhum.',
    setup: 'Filas atrás de um cone; outro cone a 10–15 m.',
    howTo: [
      'Ida e volta imitando animais: canguru (saltos a pés juntos), caranguejo (4 apoios de barriga para cima), flamingo (pé-coxinho), urso (4 apoios), lebre (sprint).',
      'Pode ser em estafeta entre filas.',
    ],
    coachingPoints: ['Aterrar com os joelhos fletidos', 'Usar os braços para equilíbrio', 'Tornar divertido: os mais novos aprendem a brincar'],
    progressions: ['Juntar bola nas mãos', 'O treinador muda o animal a meio'],
    diagram: [
      { t: 'cone', at: [15, 20] }, { t: 'cone', at: [85, 20] }, { t: 'cone', at: [15, 44] }, { t: 'cone', at: [85, 44] },
      { t: 'a', at: [10, 20] }, { t: 'a', at: [5, 20] }, { t: 'd', at: [10, 44] }, { t: 'd', at: [5, 44] },
      { t: 'run', from: [18, 20], to: [82, 20] }, { t: 'run', from: [18, 44], to: [82, 44] },
    ],
  },
  {
    id: 'saq-cones',
    name: 'Velocidade e mudança de direção',
    category: 'fisico',
    ages: [...FROM_SUB13],
    players: { min: 2, max: 20 },
    minutes: 12,
    space: '15 × 10 m',
    equipment: ['cones'],
    intensity: 'alta',
    objective: 'Arranque, travagem e mudança de direção (velocidade útil no jogo).',
    setup: 'Circuito em "T" ou em ziguezague com 4–5 cones.',
    howTo: [
      '6–8 repetições de 6–8 segundos com recuperação total (40–60 s).',
      'Terminar cada repetição com um sprint de 10 m ou com remate.',
    ],
    coachingPoints: ['Baixar o centro de gravidade antes de mudar de direção', 'Primeiros passos curtos e rápidos', 'Qualidade acima da quantidade: descansar bem'],
    progressions: ['Reagir a um sinal visual (cor/mão do treinador)', 'Em competição de pares'],
    diagram: [
      { t: 'cone', at: [20, 50] }, { t: 'cone', at: [50, 50] }, { t: 'cone', at: [50, 18] }, { t: 'cone', at: [30, 18] }, { t: 'cone', at: [70, 18] },
      { t: 'a', at: [20, 55] },
      { t: 'run', from: [22, 50], to: [48, 50] }, { t: 'run', from: [50, 48], to: [50, 20] }, { t: 'run', from: [48, 18], to: [32, 18] }, { t: 'run', from: [32, 20], to: [68, 20] },
    ],
  },
  {
    id: 'intermitente-4x4',
    name: 'Intermitente 4×4 (resistência com bola)',
    category: 'fisico',
    ages: ['sub17', 'sub19', 'senior'],
    players: { min: 8, max: 16 },
    minutes: 20,
    space: '30 × 25 m',
    equipment: ['bolas', 'cones', 'coletes', 'balizas_pequenas'],
    intensity: 'alta',
    objective: 'Resistência específica sem corridas "a seco".',
    setup: 'Jogo 4×4 com balizas pequenas; bolas de reserva à volta.',
    howTo: [
      '4 séries de 3 minutos com 2 minutos de recuperação ativa (passe a dois).',
      'Reposição de bola imediata para manter a intensidade.',
    ],
    coachingPoints: ['Não parar: pressão constante', 'Hidratação nos intervalos', 'Controlar pela perceção de esforço (RPE 7–8)'],
    progressions: ['5 séries', 'Menos espaço = mais intensidade'],
    diagram: [
      { t: 'zone', at: [12, 8], w: 76, h: 48 },
      { t: 'goal', at: [12, 32], side: 'left', small: true }, { t: 'goal', at: [88, 32], side: 'right', small: true },
      { t: 'a', at: [30, 20] }, { t: 'a', at: [34, 44] }, { t: 'a', at: [52, 30] }, { t: 'a', at: [66, 18] }, { t: 'ball', at: [54, 31] },
      { t: 'd', at: [42, 26] }, { t: 'd', at: [60, 38] }, { t: 'd', at: [72, 28] }, { t: 'd', at: [46, 46] },
      { t: 'text', at: [50, 62], text: '4 × 3 min' },
    ],
  },

  // ─── BOLAS PARADAS ───────────────────────────────────────────────────────
  {
    id: 'canto-ofensivo',
    name: 'Canto ofensivo: bloqueio e 1.º poste',
    category: 'bolas_paradas',
    ages: [...FROM_SUB13],
    players: { min: 8, max: 18 },
    minutes: 12,
    space: 'Área',
    equipment: ['bolas', 'balizas', 'coletes'],
    intensity: 'baixa',
    objective: 'Uma jogada de canto simples, fácil de memorizar.',
    setup: 'Marcador do canto, 4 atacantes em "cacho" na marca de penálti, 1 à entrada da área; defensores.',
    howTo: [
      'Ao sinal do marcador (braço levantado), um atacante bloqueia o marcador direto, outro ataca o 1.º poste, dois atacam o 2.º poste e ao centro.',
      'Repetir 6 vezes de cada lado; depois com defesa ativa.',
    ],
    coachingPoints: ['Arrancar todos ao mesmo tempo', 'Cruzamento tenso ao 1.º poste', 'Um jogador fica à entrada para a segunda bola'],
    progressions: ['Variante curta: canto a 2 com cruzamento de ângulo diferente'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'line', from: [26, 0], to: [26, 20] }, { t: 'line', from: [26, 20], to: [74, 20] }, { t: 'line', from: [74, 20], to: [74, 0] },
      { t: 'a', at: [98, 2] }, { t: 'ball', at: [96, 2] },
      { t: 'a', at: [46, 16] }, { t: 'a', at: [50, 18] }, { t: 'a', at: [54, 16] }, { t: 'a', at: [50, 14] }, { t: 'a', at: [50, 30] },
      { t: 'run', from: [54, 16], to: [60, 6] }, { t: 'run', from: [46, 16], to: [40, 7] }, { t: 'pass', from: [95, 3], to: [62, 6] },
    ],
  },
  {
    id: 'livre-direto',
    name: 'Livre direto: barreira e remate',
    category: 'bolas_paradas',
    ages: [...FROM_SUB13],
    players: { min: 3, max: 10 },
    minutes: 10,
    space: 'Entrada da área',
    equipment: ['bolas', 'balizas', 'estacas'],
    intensity: 'baixa',
    objective: 'Treinar os marcadores de livres e a organização da barreira.',
    setup: 'Barreira de 3–4 (jogadores ou estacas) a 9,15 m; GR; 2–3 marcadores.',
    howTo: [
      'Cada marcador faz 5 livres alternando por cima da barreira e ao lado do GR.',
      'GR organiza a barreira e defende.',
    ],
    coachingPoints: ['Marcador: sempre o mesmo ritual antes de bater', 'GR: barreira tapa o lado do poste próximo, GR cobre o resto'],
    progressions: ['Livre combinado: toque curto para remate de um colega'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [56, 4] },
      { t: 'd', at: [42, 18] }, { t: 'd', at: [46, 18] }, { t: 'd', at: [50, 18] },
      { t: 'ball', at: [44, 34] }, { t: 'a', at: [40, 38] },
      { t: 'shot', from: [44, 32], to: [40, 2] },
    ],
  },
  {
    id: 'defesa-canto',
    name: 'Defender cantos: zona mista',
    category: 'bolas_paradas',
    ages: [...FROM_SUB15],
    players: { min: 12, max: 20 },
    minutes: 12,
    space: 'Área',
    equipment: ['bolas', 'balizas', 'coletes'],
    intensity: 'media',
    objective: 'Organização defensiva simples em cantos contra.',
    setup: '3–4 defensores em zona (1.º poste, pequena área, marca de penálti), restantes em marcação individual aos melhores cabeceadores.',
    howTo: [
      'Atacantes executam cantos variados; defesa tem de afastar e sair em bloco até à entrada da área.',
      'Contar cantos defendidos sem remate enquadrado.',
    ],
    coachingPoints: ['Atacar a bola, não esperar por ela', 'Na marcação individual, ver bola e adversário', 'Depois de afastar, sair todos juntos'],
    progressions: ['Juntar contra-ataque depois de recuperar'],
    diagram: [
      { t: 'goal', at: [50, 0], side: 'top' }, { t: 'gk', at: [50, 4] },
      { t: 'line', from: [26, 0], to: [26, 20] }, { t: 'line', from: [26, 20], to: [74, 20] }, { t: 'line', from: [74, 20], to: [74, 0] },
      { t: 'd', at: [40, 5] }, { t: 'd', at: [44, 10] }, { t: 'd', at: [56, 10] }, { t: 'd', at: [50, 16] },
      { t: 'd', at: [46, 22] }, { t: 'a', at: [47, 24] }, { t: 'd', at: [58, 20] }, { t: 'a', at: [59, 22] },
      { t: 'a', at: [98, 2] }, { t: 'ball', at: [96, 2] },
    ],
  },
];
