import type { AgeGuide, SessionPlan } from './types';

export const SESSION_PLANS: SessionPlan[] = [
  {
    id: 'petizes-divertir-com-bola',
    name: 'Petizes: divertir-se com a bola',
    ages: ['sub7'],
    theme: 'Condução e jogo',
    minutes: 50,
    summary: 'Cada criança com a sua bola a maior parte do tempo e muito jogo. Pouca fila, pouca conversa.',
    blocks: [
      { drillId: 'semaforo', minutes: 8 },
      { drillId: 'coordenacao-animais', minutes: 7 },
      { drillId: 'piratas-tesouro', minutes: 10 },
      { drillId: 'festival-4x4', minutes: 25, note: '3×3 sem guarda-redes' },
    ],
  },
  {
    id: 'traquinas-drible',
    name: 'Traquinas: drible e 1×1',
    ages: ['sub9'],
    theme: 'Drible',
    minutes: 60,
    summary: 'Ganhar confiança para ultrapassar adversários. Elogiar a tentativa, não só o sucesso.',
    blocks: [
      { drillId: 'apanhada-caudas', minutes: 8 },
      { drillId: 'fintas-quadrado', minutes: 10 },
      { drillId: 'drible-portas', minutes: 12 },
      { drillId: 'conducao-remate', minutes: 10 },
      { drillId: '3x3-quatro-balizas', minutes: 20 },
    ],
  },
  {
    id: 'benjamins-passe',
    name: 'Benjamins: passe e receção',
    ages: ['sub11'],
    theme: 'Passe',
    minutes: 70,
    summary: 'Do passe técnico ao passe com oposição, terminando em jogo onde o passe dá pontos.',
    blocks: [
      { drillId: 'estafetas-slalom', minutes: 8 },
      { drillId: 'passe-segue-linhas', minutes: 8 },
      { drillId: 'rececao-orientada-triangulo', minutes: 10 },
      { drillId: 'meinho-4x1', minutes: 12 },
      { drillId: 'jogo-das-portas', minutes: 12 },
      { drillId: 'festival-4x4', minutes: 20 },
    ],
  },
  {
    id: 'benjamins-finalizacao',
    name: 'Benjamins: finalização',
    ages: ['sub11', 'sub13'],
    theme: 'Finalização',
    minutes: 70,
    summary: 'Muitos remates por jogador em situações parecidas com o jogo.',
    blocks: [
      { drillId: 'apanhada-caudas', minutes: 8 },
      { drillId: 'conducao-remate', minutes: 15 },
      { drillId: 'tabela-remate', minutes: 12 },
      { drillId: '2x1-finalizacao', minutes: 15 },
      { drillId: '3x3-quatro-balizas', minutes: 20, note: 'Golos de primeira valem 2' },
    ],
  },
  {
    id: 'infantis-posse',
    name: 'Infantis: posse de bola',
    ages: ['sub13'],
    theme: 'Posse e apoios',
    minutes: 70,
    summary: 'Ocupar bem o espaço para manter a bola: apoios, largura e mudança de lado.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 8 },
      { drillId: 'meinho-4x1', minutes: 10 },
      { drillId: 'rondo-5x2', minutes: 12 },
      { drillId: 'posse-4x4-jokers', minutes: 15 },
      { drillId: 'jogo-7x7-zonas', minutes: 25, note: 'Condição: 5 passes antes de passar a zona média' },
    ],
  },
  {
    id: 'infantis-1x1',
    name: 'Infantis: atacar e defender o 1×1',
    ages: ['sub13', 'sub15'],
    theme: 'Duelos',
    minutes: 70,
    summary: 'Duelos ofensivos e defensivos, a base de tudo o resto.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 8 },
      { drillId: 'fintas-quadrado', minutes: 10 },
      { drillId: '1x1-defensivo-corredor', minutes: 12 },
      { drillId: '2x2-coberturas', minutes: 15 },
      { drillId: 'jogo-7x7-zonas', minutes: 25, note: '1×1 ganho na zona ofensiva vale 1 ponto' },
    ],
  },
  {
    id: 'iniciados-transicoes',
    name: 'Iniciados: transições',
    ages: ['sub15', 'sub17'],
    theme: 'Transição ataque-defesa',
    minutes: 85,
    summary: 'O que fazer nos 5 segundos depois de ganhar ou perder a bola.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 10 },
      { drillId: 'rondo-5x2', minutes: 10 },
      { drillId: 'quem-marca-fica', minutes: 15 },
      { drillId: 'contra-ataque-3x2-ondas', minutes: 15 },
      { drillId: 'pressao-5-segundos', minutes: 15 },
      { drillId: 'jogo-7x7-zonas', minutes: 20 },
    ],
  },
  {
    id: 'iniciados-defesa',
    name: 'Iniciados/Juvenis: organização defensiva',
    ages: ['sub15', 'sub17', 'sub19'],
    theme: 'Defesa em bloco',
    minutes: 80,
    summary: 'Do 1×1 ao comportamento da linha defensiva.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 10 },
      { drillId: '1x1-defensivo-corredor', minutes: 12 },
      { drillId: '2x2-coberturas', minutes: 15 },
      { drillId: 'linha-4-basculacao', minutes: 18 },
      { drillId: 'jogo-7x7-zonas', minutes: 25, note: 'Recuperar na zona média vale 1 ponto' },
    ],
  },
  {
    id: 'juvenis-pressao',
    name: 'Juvenis/Juniores: pressão e recuperação',
    ages: ['sub17', 'sub19', 'senior'],
    theme: 'Pressão',
    minutes: 80,
    summary: 'Pressionar juntos logo após a perda e recuperar em zonas altas.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 10 },
      { drillId: 'rondo-5x2', minutes: 12 },
      { drillId: 'pressao-5-segundos', minutes: 18 },
      { drillId: 'posse-4x4-jokers', minutes: 15 },
      { drillId: 'jogo-7x7-zonas', minutes: 25, note: 'Recuperar na zona ofensiva vale 1 ponto' },
    ],
  },
  {
    id: 'seniores-md3',
    name: 'Seniores: 3 dias antes do jogo (intensidade)',
    ages: ['sub19', 'senior'],
    theme: 'Treino mais exigente da semana',
    minutes: 85,
    summary: 'Pico de carga da semana: espaços reduzidos, muita intensidade, tema tático do próximo jogo.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 12 },
      { drillId: 'rondo-5x2', minutes: 10 },
      { drillId: 'intermitente-4x4', minutes: 20 },
      { drillId: 'contra-ataque-3x2-ondas', minutes: 15 },
      { drillId: 'jogo-7x7-zonas', minutes: 28 },
    ],
  },
  {
    id: 'seniores-md1',
    name: 'Seniores: véspera de jogo (ativação e bolas paradas)',
    ages: ['sub17', 'sub19', 'senior'],
    theme: 'Frescura e estratégia',
    minutes: 60,
    summary: 'Pouco volume, muita velocidade de execução e bolas paradas preparadas para o jogo.',
    blocks: [
      { drillId: 'ativacao-dinamica', minutes: 10 },
      { drillId: 'meinho-4x1', minutes: 8 },
      { drillId: 'saq-cones', minutes: 8, note: 'Só 4 repetições' },
      { drillId: 'canto-ofensivo', minutes: 12 },
      { drillId: 'defesa-canto', minutes: 10 },
      { drillId: 'livre-direto', minutes: 12 },
    ],
  },
  {
    id: 'guarda-redes',
    name: 'Guarda-redes: sessão específica',
    ages: ['sub13', 'sub15', 'sub17', 'sub19', 'senior'],
    theme: 'Guarda-redes',
    minutes: 45,
    summary: 'Para fazer num canto do campo enquanto o resto da equipa treina (pode ser orientado por um pai ou colega).',
    blocks: [
      { drillId: 'coordenacao-animais', minutes: 6, note: 'Versão: saltos laterais e quedas' },
      { drillId: 'gr-posicao-encaixe', minutes: 12 },
      { drillId: 'gr-saidas-1x1', minutes: 12 },
      { drillId: 'gr-jogo-pes', minutes: 15 },
    ],
  },
  {
    id: 'pouco-material',
    name: 'Treino com 8 jogadores e só bolas e cones',
    ages: ['sub11', 'sub13', 'sub15', 'sub17', 'sub19', 'senior'],
    theme: 'Poucos recursos',
    minutes: 70,
    summary: 'Poucos jogadores, sem balizas nem coletes suficientes? Este treino funciona na mesma: balizas feitas com cones e muito jogo.',
    blocks: [
      { drillId: 'apanhada-caudas', minutes: 8, note: 'Sem coletes: usar uma meia no calção' },
      { drillId: 'meinho-4x1', minutes: 12 },
      { drillId: 'drible-portas', minutes: 12 },
      { drillId: 'quem-marca-fica', minutes: 18, note: 'Balizas de dois cones' },
      { drillId: '3x3-quatro-balizas', minutes: 20 },
    ],
  },
];

/** What matters at each age — a mini-methodology for coaches without a coordinator. */
export const AGE_GUIDES: AgeGuide[] = [
  {
    age: 'sub7',
    format: 'Festivais 3×3 / Futebol 5',
    priorities: ['Uma bola por criança sempre que possível', 'Condução, drible e remate', 'Jogos com regras simples', 'Diversão e vontade de voltar'],
    avoid: ['Filas e esperas longas', 'Posições fixas', 'Corridas sem bola', 'Explicações de mais de 30 segundos'],
    sessionShape: '45–60 min · 2–3 jogos lúdicos + 20–25 min de jogo',
  },
  {
    age: 'sub9',
    format: 'Futebol 5',
    priorities: ['1×1 ofensivo (drible)', 'Remate com os dois pés', 'Primeiras noções de passe', 'Todos jogam o mesmo tempo'],
    avoid: ['Pontapé para a frente como solução', 'Especializar guarda-redes cedo', 'Gritar instruções durante o jogo'],
    sessionShape: '60 min · técnica em jogo + muito jogo reduzido',
  },
  {
    age: 'sub11',
    format: 'Futebol 7',
    priorities: ['Passe e receção orientada', 'Desmarcação e apoios', '1×1 ofensivo e defensivo', 'Rodar todas as posições'],
    avoid: ['Esquemas táticos complexos', 'Treino físico isolado', 'Jogar sempre os mesmos'],
    sessionShape: '60–75 min · aquecimento com bola, 2 exercícios do tema, jogo condicionado',
  },
  {
    age: 'sub13',
    format: 'Futebol 7 ou 9 (conforme a Associação)',
    priorities: ['Posse de bola e ocupação do espaço', 'Princípios defensivos (pressão, cobertura)', 'Tomada de decisão', 'Técnica sob pressão'],
    avoid: ['Resultados acima da formação', 'Carga física de adulto', 'Excluir quem está em crescimento tardio'],
    sessionShape: '75 min · 3 treinos por semana no máximo',
  },
  {
    age: 'sub15',
    format: 'Futebol 11',
    priorities: ['Organização coletiva (linhas, basculação)', 'Transições', 'Posições específicas', 'Força com o peso do corpo'],
    avoid: ['Ignorar o crescimento (dores, lesões)', 'Sessões longas sem bola'],
    sessionShape: '75–90 min · tema tático semanal',
  },
  {
    age: 'sub17',
    format: 'Futebol 11',
    priorities: ['Modelo de jogo da equipa', 'Intensidade de jogo', 'Bolas paradas', 'Responsabilidade e autonomia'],
    avoid: ['Picos de carga sem controlo (usar RPE)', 'Descurar recuperação e sono'],
    sessionShape: '90 min · microciclo com dia mais intenso a meio da semana',
  },
  {
    age: 'sub19',
    format: 'Futebol 11',
    priorities: ['Competitividade e ritmo sénior', 'Estratégia por adversário', 'Liderança dentro do grupo'],
    avoid: ['Treinar sempre igual', 'Ignorar o bem-estar (estudos, trabalho)'],
    sessionShape: '90 min · controlo de carga semanal',
  },
  {
    age: 'senior',
    format: 'Futebol 11',
    priorities: ['Preparação do jogo da semana', 'Gestão da carga e recuperação', 'Bolas paradas', 'Coesão do grupo'],
    avoid: ['Treino mais intenso na véspera', 'Corridas longas sem objetivo'],
    sessionShape: 'Semana tipo: recuperação → força/tática → intensidade → velocidade → ativação',
  },
];
